apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amishipatidar/Session-20-Monitoring-Observability-GitOps.git'
    targetRevision: HEAD
    path: gitops-demo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
