apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enterprise-web-chart.fullname" . }}-config
data:
  DB_HOST: {{ .Values.config.databaseHost | quote }}
  DB_PORT: {{ .Values.config.databasePort | quote }}
  ENABLE_CACHING: {{ .Values.config.enableCaching | quote }}
