apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enterprise-web-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "enterprise-web-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "enterprise-web-chart.fullname" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "enterprise-web-chart.fullname" . }}-config
            - secretRef:
                name: {{ include "enterprise-web-chart.fullname" . }}-secret
