apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-web-chart.fullname" . }}-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASS: {{ .Values.secret.dbPassword | quote }}
