apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise-web-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "enterprise-web-chart.fullname" . }}
